POST http://localhost:3000/auth/signup
Content-Type: application/json


{
  "name": "John Doe",
  "email": "johndoe@email.com",
  "password": "senha"
}

###
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "johndoe@email.com",
  "password": "senha"
  }